framework:
    messenger:
        default_bus: messenger.bus.command
        failure_transport: failed
        buses:
            messenger.bus.command:
                default_middleware: false
                middleware:
                    - handle_message

            messenger.bus.query:
                default_middleware: false
                middleware:
                    - handle_message

            messenger.bus.event.async:
                default_middleware: allow_no_handlers
        transports:
            events:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
         
            failed:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
          
