version: "3.8"
services:
    db:
        image: mariadb:10.9.4
        platform: linux/x86_64
        restart: always
        volumes:
            - "db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - app
    php:
        build:
          context: ./tools/docker/php
          args:
              TIMEZONE: ${TIMEZONE}
        platform: linux/x86_64
        depends_on:
        - db
        environment:
        - APP_ENV=${APP_ENV}
        - APP_SECRET=${APP_SECRET}
        - DATABASE_URL=${DATABASE_URL}
        volumes:
        - ./:/var/www
        - ./tools/docker/php/php.ini:/usr/local/etc/php/php.ini:ro
        networks:
        - app
    nginx:
        build:
            context: ./tools/docker/nginx
        volumes:
            - ./:/var/www
        ports:
            - 80:80
        networks:
            - app
    rmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"      
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
      networks:
        - app        
    redis:
        image: redis:6.2.6
        ports:
        - "6379:6379"
        volumes:
        - ./docker/data/redis/data:/var/lib/redis
        - ./docker/data/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
        - REDIS_REPLICATION_MODE=master
        networks:
            - app  
volumes:
    db:
networks:
    app:

